### ISSUE TITLE
Shuttle Turfs Are REALLY Fucked up

### ISSUE THREAD

**Issue by unit0016** [TetraStation/TetraStation#12]
![image](https://user-images.githubusercontent.com/50649185/208783275-695c0268-b7a2-42f6-a5c6-101a911bc5c6.png)

We don't have much info on this. At all. Needs major debugging. (Possibly related to #7 somehow?)

**Comment by TamberP** [comment]
Something, somewhere, is trying to smooth those floor tiles. (I suspect icon_smoothing)
The icon state is being changed from e.g. `dark_anticorner` into `smooth`, which doesn't exist in `icons/turf/floors.dmi`.

As seen here by the quick creation of a very horrible and obvious `smooth` icon_state.
![Screenshot_2022-12-22_05-24-58](https://user-images.githubusercontent.com/1147817/209063714-10aa3168-9832-40f9-8807-feccdaeea04c.png)

**Comment by TamberP** [comment]
Even with the relevant turfs being set with `canSmoothWith` as null, by the time we get to the infiltrator, they've somehow been set to `canSmoothWith = [17]`, which crossreferences to `SMOOTH_GROUP_CARPET_RED`, for some reason.

**Comment by TamberP** [comment]
oh, wait, that's normal. I'm barking up the wrong tree there.

**Comment by TamberP** [comment]
So... wait, hm.
Those dark plasteel turfs without a turf_decal on 'em are fine. When a turf_decal gets overlaid, they suddenly become `smooth`? What the fuck?

**Comment by TamberP** [comment]
![Screenshot_2022-12-22_15-41-51](https://user-images.githubusercontent.com/1147817/209170903-e7e61689-3ebc-467a-8ae6-2c876f59938e.png)
And it appears to just be limited to the shuttle areas. That's the `dark_anticorner ` with a turf_decal on it, on-station, and it ... works just fine?

I AM EXTREMELY CONFUSED AND OUT OF MY DEPTH

**Comment by TamberP** [comment]
![Screenshot_2022-12-22_15-53-15](https://user-images.githubusercontent.com/1147817/209172318-5676ddce-bebe-44b9-af4a-a958765995c2.png)
Ugly bodge in place temporarily until we can figure out what the fuck is going on.
