### ISSUE TITLE
Gen Turf was premature, Lavaland + Icemoon generate NO minerals

### ISSUE THREAD

**Issue by unit0016** [TetraStation/TetraStation#23]
So, turns out that generation was refactored on /tg/ before this was added! And it was a prerequisite to make gen turf not completely destroy generation!

...Oops!

**Comment by unit0016** [comment]
Relevant /tg/station PR here:
https://github.com/tgstation/tgstation/pull/54915

We'll have to update rust for this, oh gee golly.

**Comment by TamberP** [comment]
Rust tentatively updated to 1.2.0.

**Comment by unit0016** [comment]
Closed by #24
